Bugfix/models
Studio-Yandex-Practicum/adaptive_hockey_federation pull request #35
Opened 2023-11-11 08:39 UTC by AntiANT8406

Добавлены основные модели для функционирования логики проекта. Возможно будут нужны дополнительные ограничения и методы. Так же добавил модель пользователя. Closes #28

2023-11-13 21:24 UTC, Raidzin requested changes
Всё супер!) Небольшие опечатки и не совсем понятно, для чего модель `Role`

2023-11-13 21:24 UTC, Raidzin commented on adaptive_hockey_federation/main/models.py
> +class Anamnes(BaseUniqueName):
Пишется `Anamnesis`

2023-11-13 21:24 UTC, Raidzin commented on adaptive_hockey_federation/main/models.py
> +        verbose_name='Дигноз или числовой статус',
Очепятка

2023-11-13 21:24 UTC, Raidzin commented on adaptive_hockey_federation/main/models.py
> +class Role(BaseUniqueName):
Для чего эта модель? (не нашёл где она используется)

2023-11-16 17:54 UTC, AntiANT8406 commented
Исправил ошибки и добавил ещё моделей. Возможно некоторые из них так и не потребуются в проекте. Ещё хочется добавить ограничений, но без работы с парсером это кажется преждевременным. closes #28

2023-11-25 15:27 UTC, closed without merging